spring:
  datasource:
    url: ${GRAPH_JDBC_CONNECTION:jdbc:postgresql://localhost:5432/graph}
    username: ${GRAPH_JDBC_USER:graph}
    password: ${GRAPH_JDBC_PASSWORD:graph}
  flyway:
    user: ${GRAPH_JDBC_USER:graph}
    password: ${GRAPH_JDBC_PASSWORD:graph}
    url: ${GRAPH_JDBC_CONNECTION_FLYWAY:jdbc:postgresql://localhost:5432/graph}
    enabled: ${GRAPH_MIGRATION_ENABLED:true}
  jpa:
    hibernate:
      ddl-auto: ${GRAPH_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: public

server:
  port: ${GRAPH_SERVER_PORT:8888}
  servlet.context-path: ${GRAPH_CONTEXT_PATH:/api}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO